package com.nexe.entity;

import java.util.Collection;
import java.util.Collections;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import jakarta.persistence.*;

/**
 * USER ENTITY
 *
 * PURPOSE:
 * - Represents a user record in the database
 * - Maps to the "users" table
 * - Implements UserDetails so Spring Security can use it
 *   for authentication and authorization
 *
 * WHY IMPLEMENT UserDetails?
 * - Spring Security expects authenticated users to implement
 *   the UserDetails interface.
 * - This allows Spring Security to directly use this entity
 *   during login and JWT validation.
 */
@Entity
@Table(
    name = "users",
    uniqueConstraints = {
        @UniqueConstraint(columnNames = "username"),
        @UniqueConstraint(columnNames = "email")
    }
)
public class User implements UserDetails {

    /**
     * PRIMARY KEY
     *
     * PURPOSE:
     * - Uniquely identifies each user in the database
     * - Auto-generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * USERNAME
     *
     * PURPOSE:
     * - Used for login authentication
     * - Must be unique
     *
     * DATABASE:
     * - NOT NULL
     * - UNIQUE
     */
    @Column(nullable = false, unique = true)
    private String username;

    /**
     * EMAIL
     *
     * PURPOSE:
     * - Stores the user's email address
     * - Can be used for notifications, password reset,
     *   account verification, etc.
     *
     * DATABASE:
     * - NOT NULL
     * - UNIQUE
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * USER ROLE
     *
     * PURPOSE:
     * - Defines permissions granted to the user
     * - Used by Spring Security for authorization
     *
     * DATABASE:
     * - Stored as String
     * - Example: ROLE_USER, ROLE_ADMIN
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    /**
     * PASSWORD
     *
     * PURPOSE:
     * - Stores encrypted password (BCrypt hash)
     *
     * SECURITY:
     * - Never store plain text passwords
     * - Always encode before saving
     */
    @Column(nullable = false)
    private String password;

    /**
     * DEFAULT CONSTRUCTOR
     *
     * REQUIRED BY:
     * - JPA/Hibernate
     */
    public User() {
    }

    /**
     * PARAMETERIZED CONSTRUCTOR
     *
     * PURPOSE:
     * - Convenient way to create users
     */
    public User(String username, String email, String password, Role role) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.role = role;
    }

    /**
     * GET USER ID
     */
    public Long getId() {
        return id;
    }

    /**
     * SET USER ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * GET USERNAME
     *
     * OVERRIDDEN FROM UserDetails
     */
    @Override
    public String getUsername() {
        return username;
    }

    /**
     * SET USERNAME
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * GET EMAIL
     */
    public String getEmail() {
        return email;
    }

    /**
     * SET EMAIL
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * GET ROLE
     */
    public Role getRole() {
        return role;
    }

    /**
     * SET ROLE
     */
    public void setRole(Role role) {
        this.role = role;
    }

    /**
     * GET PASSWORD
     *
     * OVERRIDDEN FROM UserDetails
     */
    @Override
    public String getPassword() {
        return password;
    }

    /**
     * SET PASSWORD
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * USER AUTHORITIES
     *
     * PURPOSE:
     * - Converts Role enum into Spring Security authority
     * - Example:
     *   ROLE_USER  -> GrantedAuthority("ROLE_USER")
     *   ROLE_ADMIN -> GrantedAuthority("ROLE_ADMIN")
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return Collections.singletonList(
                new SimpleGrantedAuthority(role.name())
        );
    }

    /**
     * ACCOUNT EXPIRATION STATUS
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * ACCOUNT LOCK STATUS
     */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * CREDENTIAL EXPIRATION STATUS
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * ACCOUNT ENABLED STATUS
     */
    @Override
    public boolean isEnabled() {
        return true;
    }
}