package com.nexe.entity;

import java.util.Collection;
import java.util.Collections;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import jakarta.persistence.*;

/**
 * USER ENTITY
 *
 * PURPOSE:
 * - Represents a user record in the database
 * - Maps to the "users" table
 * - Implements UserDetails so Spring Security can use it
 *   for authentication and authorization
 *
 * WHY IMPLEMENT UserDetails?
 * - Spring Security expects authenticated users to implement
 *   the UserDetails interface.
 * - This allows Spring Security to directly use this entity
 *   during login and JWT validation.
 */
@Entity
@Table(
    name = "users",
    uniqueConstraints = {
        @UniqueConstraint(columnNames = "username")
    }
)
public class User implements UserDetails {

    /**
     * PRIMARY KEY
     *
     * PURPOSE:
     * - Uniquely identifies each user in the database
     * - Auto-generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * USERNAME
     *
     * PURPOSE:
     * - Used for login authentication
     * - Must be unique
     *
     * DATABASE:
     * - NOT NULL
     * - UNIQUE
     */
    @Column(nullable = false, unique = true)
    private String username;

    /**
     * PASSWORD
     *
     * PURPOSE:
     * - Stores encrypted password (BCrypt hash)
     *
     * SECURITY:
     * - Never store plain text passwords
     * - Always encode before saving
     */
    private String password;

    /**
     * DEFAULT CONSTRUCTOR
     *
     * REQUIRED BY:
     * - JPA/Hibernate
     * - Object creation during database operations
     */
    public User() {}

    /**
     * PARAMETERIZED CONSTRUCTOR
     *
     * PURPOSE:
     * - Convenient way to create users
     */
    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    /**
     * GET USER ID
     */
    public Long getId() {
        return id;
    }

    /**
     * SET USER ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * GET USERNAME
     *
     * OVERRIDDEN FROM UserDetails
     *
     * PURPOSE:
     * - Spring Security uses this during authentication
     * - Returns unique login identifier
     */
    @Override
    public String getUsername() {
        return username;
    }

    /**
     * SET USERNAME
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * GET PASSWORD
     *
     * OVERRIDDEN FROM UserDetails
     *
     * PURPOSE:
     * - Spring Security uses this to verify credentials
     */
    @Override
    public String getPassword() {
        return password;
    }

    /**
     * SET PASSWORD
     *
     * NOTE:
     * - Password should already be encoded before storing
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * USER ROLES / AUTHORITIES
     *
     * PURPOSE:
     * - Defines permissions assigned to the user
     *
     * CURRENT IMPLEMENTATION:
     * - No roles assigned
     * - Returns empty authority list
     *
     * EXAMPLE (future):
     * - ROLE_USER
     * - ROLE_ADMIN
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return Collections.emptyList();
    }

    /**
     * ACCOUNT EXPIRATION STATUS
     *
     * PURPOSE:
     * - Determines whether account has expired
     *
     * CURRENT:
     * - Always valid
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * ACCOUNT LOCK STATUS
     *
     * PURPOSE:
     * - Determines whether account is locked
     *
     * CURRENT:
     * - Never locked
     */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * CREDENTIAL EXPIRATION STATUS
     *
     * PURPOSE:
     * - Determines whether password has expired
     *
     * CURRENT:
     * - Never expires
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * ACCOUNT ENABLED STATUS
     *
     * PURPOSE:
     * - Determines whether account is active
     *
     * CURRENT:
     * - Always enabled
     */
    @Override
    public boolean isEnabled() {
        return true;
    }
}